routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'auth.admin'])->group(function() {
    //USERS
    Route::resource('/users', 'App\Http\Controllers\UsersController')->except(['show', 'destroy']);

    //SECTIONS
    Route::resource('/sections', 'App\Http\Controllers\SectionsController')->except(['show', 'destroy']);
    
    //CONSOLIDATE
    Route::get('/consolidate', 'App\Http\Controllers\ConsolidateController@index')->name('consolidate');
    Route::get('/consolidate/{section}', 'App\Http\Controllers\ConsolidateController@show')->name('consolidate.show');
});

Route::middleware(['auth', 'auth.jury'])->group(function() {
    //PROJECTS
    Route::resource('/projects', 'App\Http\Controllers\ProjectsController');

    //CHECK
    Route::get('/check', 'App\Http\Controllers\CheckController@index')->name('checklist');
    Route::get('/check/{project}', 'App\Http\Controllers\CheckController@check')->name('check');
    Route::post('/check/{project}', 'App\Http\Controllers\CheckController@store')->name('check.store');
    Route::get('/check/{project}/edit', 'App\Http\Controllers\CheckController@edit')->name('check.edit');
    Route::get('/check/{project}/show', 'App\Http\Controllers\CheckController@show')->name('check.show');
    Route::put('/check/{project}/update', 'App\Http\Controllers\CheckController@update')->name('check.update');
});

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Result;

class Project extends Model
{
    use HasFactory;

    protected $fillable = ['fullname', 'organization', 'stage', 'section_id', 'link', 'city'];

    public function section()
    {
        return $this->belongsTo('App\Models\Section');
    }

    public function getResultFromUser($userId)
    {
        return Result::where('project_id', $this->id)->where('jury_id', $userId)->firstOrFail();
    }

    public function hasResultFromUser($userId)
    {
        if (Result::where('project_id', $this->id)->where('jury_id', $userId)->get()->isEmpty()) {
            return false;
        }
        return true;
    }

    public function hasResultFromCurrentUser()
    {
        return $this->hasResultFromUser(auth()->user()->id);
    }

    public function getResultFromCurrentUser()
    {
        return $this->getResultFromUser(auth()->user()->id);
    }

    public function getAllResults()
    {
        return Result::where('project_id', $this->id)->get();
    }

    public function getFirstPartScore()
    {
        $results = $this->getAllResults();
        $score = $results->avg(function($result) {
            return $result->sumOfFirstPart();
        });
        return $score;
    }

    public function getSecondPartScore()
    {
        $results = $this->getAllResults();
        $score = $results->avg(function($result) {
            return $result->sumOfSecondPart();
        });
        return $score;
    }

    public function getTotalScore()
    {
        $results = $this->getAllResults();
        $score = $results->avg(function($result) {
            return $result->sumOfAll();
        });
        return $score;
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;

class ProjectsController extends Controller
{
    public function index()
    {
        return view('projects.index');
    }

    public function create()
    {
        return view('projects.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'section_id' => 'required',
            'fullname' => 'required',
            'organization' => 'required',
            'stage' => 'required|integer|min:1|max:11',
            'city' => '',
            'link' => 'required',
        ],[
            'section_id.required' => 'Секция не выбрана',
            'fullname.required' => 'Укажите Фамилию, Имя и Отчество автора',
            'organization.required' => 'Укажите наименование образовательного учреждения',
            'stage.required' => 'Укажите класс',
            'stage.integer' => 'Укажите только цифру',
            'link.required' => 'Укажите ссылку на проект',
        ]);

        if (! \Gate::allows('work-with-project', $request->input('section_id'))) {
            return abort(403);
        }

        $project = Project::create($validatedData);

        return redirect(route('projects.index'));
    }

    public function edit(Project $project)
    {
        if (! \Gate::allows('work-with-project', $project->section->id)) {
            return abort(403);
        }

        return view('projects.edit', compact(['project']));
    }

    public function update(Request $request, Project $project)
    {
        if (! \Gate::allows('work-with-project', $request->input('section_id'))) {
            return abort(403);
        }

        $validatedData = $request->validate([
            'section_id' => 'required',
            'fullname' => 'required',
            'organization' => 'required',
            'stage' => 'required|integer',
            'city' => '',
            'link' => 'required',
        ],[
            'section_id.required' => 'Секция не выбрана',
            'fullname.required' => 'Укажите Фамилию, Имя и Отчество автора',
            'organization.required' => 'Укажите наименование образовательного учреждения',
            'stage.required' => 'Укажите класс',
            'stage.integer' => 'Укажите только цифру',
            'link.required' => 'Укажите ссылку на проект',
        ]);

        $project->update($validatedData);

        return redirect(route('projects.index'));
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Добавление работы</h2>
            <form action="{{ route('projects.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="section">Выберите секцию</label>
                    @error('section_id')
                        <div class="invalid-feedback d-block">
                            {{ $message }}
                        </div>
                    @enderror
                    <select class="custom-select" name="section_id">
                        @foreach(auth()->user()->sections as $section)
                        <option value="{{ $section->id }}">{{ $section->name }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="fullname">ФИО</label>
                    @error('fullname')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="fullname" name="fullname">
                </div>
                <div class="form-group">
                    <label for="organization">Наименование образовательного учреждения </label>
                    @error('organization')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="organization" name="organization">
                </div>
                <div class="form-group">
                    <label for="stage">Класс</label>
                    @error('stage')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="number" min="1" max="11" class="form-control" id="stage" name="stage">
                </div>
                <div class="form-group">
                    <label for="city">Город (По умолчанию: Калининград)</label>
                    <input type="text" class="form-control" id="city" name="city" value="Калининград">
                </div>
                <div class="form-group">
                    <label for="link">Ссылка на проект</label>
                    @error('link')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="link" name="link">
                </div>
                <input type="submit" value="Сохранить работу" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Изменение проекта</h2>
            <form action="{{ route('projects.update', $project->id) }}" method="post">
                @csrf
                @method('PUT')
                <input type="hidden" name="id" value="{{ $project->id }}">
                <div class="form-group">
                    <label for="section">Выберите секцию</label>
                    @error('section_id')
                        <div class="invalid-feedback d-block">
                            {{ $message }}
                        </div>
                    @enderror
                    <select class="custom-select" name="section_id">
                        @foreach(auth()->user()->sections as $section)
                        <option value="{{ $section->id }}" {{ $section->id == $project->section->id ? 'selected' : '' }}>{{ $section->name }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="fullname">ФИО</label>
                    @error('fullname')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="fullname" name="fullname" value="{{ $project->fullname }}">
                </div>
                <div class="form-group">
                    <label for="organization">Наименование образовательного учреждения </label>
                    @error('organization')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="organization" name="organization" value="{{ $project->organization }}">
                </div>
                <div class="form-group">
                    <label for="stage">Класс</label>
                    @error('stage')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="number" min="1" max="11" class="form-control" id="stage" name="stage" value="{{ $project->stage }}">
                </div>
                <div class="form-group">
                    <label for="city">Город (По умолчанию: Калининград)</label>
                    <input type="text" class="form-control" id="city" name="city" value="{{ $project->city }}">
                </div>
                <div class="form-group">
                    <label for="link">Ссылка на проект</label>
                    @error('link')
                    <div class="invalid-feedback d-block">
                        {{ $message }}
                    </div>
                    @enderror
                    <input type="text" class="form-control" id="link" name="link" value="{{ $project->link }}">
                </div>
                <input type="submit" value="Сохранить проект" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h2>Работы</h2>
            <a href="{{ route('projects.create') }}" class="btn btn-primary mt-5 mb-5">Добавть работу</a><br>
            @foreach(auth()->user()->sections as $section)
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#section-{{ $section->id }}" aria-expanded="false" aria-controls="collapseOne">
                        {{ $section->name }}
                        <span class="badge badge-info ml-3">{{ $section->projects->count() }}</span>
                        </button>
                    </h2>
                    </div>

                    <div id="section-{{ $section->id }}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">ФИО</th>
                                        <th scope="col">ОУ</th>
                                        <th scope="col">Класс</th>
                                        <th scope="col">Ссылка</th>
                                        <th scope="col">Редактировать</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @forelse($section->projects as $project) 
                                    <tr>
                                        <th scope="col">{{ $project->fullname }}</th>
                                        <th scope="col">{{ $project->organization }}</th>
                                        <th scope="col">{{ $project->stage }}</th>
                                        <th scope="col"><a href="{{ $project->link }}">Открыть работу</a></th>
                                        <th scope="col"><a href="{{ route('projects.edit', $project->id) }}">Редактировать</a></th>
                                    </tr>
                                @empty

                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
@endsection