routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'auth.admin'])->group(function() {
    //USERS
    Route::resource('/users', 'App\Http\Controllers\UsersController')->except(['show', 'destroy']);

    //SECTIONS
    Route::resource('/sections', 'App\Http\Controllers\SectionsController')->except(['show', 'destroy']);
    
    //CONSOLIDATE
    Route::get('/consolidate', 'App\Http\Controllers\ConsolidateController@index')->name('consolidate');
    Route::get('/consolidate/{section}', 'App\Http\Controllers\ConsolidateController@show')->name('consolidate.show');
});

Route::middleware(['auth', 'auth.jury'])->group(function() {
    //PROJECTS
    Route::resource('/projects', 'App\Http\Controllers\ProjectsController');

    //CHECK
    Route::get('/check', 'App\Http\Controllers\CheckController@index')->name('checklist');
    Route::get('/check/{project}', 'App\Http\Controllers\CheckController@check')->name('check');
    Route::post('/check/{project}', 'App\Http\Controllers\CheckController@store')->name('check.store');
    Route::get('/check/{project}/edit', 'App\Http\Controllers\CheckController@edit')->name('check.edit');
    Route::get('/check/{project}/show', 'App\Http\Controllers\CheckController@show')->name('check.show');
    Route::put('/check/{project}/update', 'App\Http\Controllers\CheckController@update')->name('check.update');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'school_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole($role) {
        return $this->roles->contains(\App\Models\Role::where('name', $role)->first());
    }

    public function isAdmin() {
        return $this->hasRole('admin');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

    public function sections()
    {
        return $this->belongsToMany('App\Models\Section', 'user_section');
    }

    public function scopeJuriesOnly($query)
    {
        return $query->whereHas('roles', function($q) {
            $q->where('id', 2);
        });
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use \App\Models\User;
use \App\Models\Role;
use \App\Models\Section;

class UsersController extends Controller
{
    public function index() 
    {
        $users = User::all();
        return view('users.index', compact(['users']));
    }

    public function create() 
    {
        $roles = Role::all();
        $sections = Section::all();
        return view('users.create', compact(['roles', 'sections']));
    }

    public function store(Request $request) 
    {
        $user = User::create([
            'name' => $request->input('login'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
        ]);

        $user->roles()->attach($request->input('roles'));
        $user->sections()->attach($request->input('sections'));

        return redirect(route('users.index'));
    }

    public function edit(User $user) 
    {
        $roles = Role::all();
        $sections = Section::all();
        return view('users.edit', compact(['user', 'roles', 'sections']));
    }

    public function update(Request $request, User $user) 
    {
        $user->name = $request->input('login');
        $user->email = $request->input('email');

        if ($request->has('password') && $request->input('password') != '') {
            $user->password = Hash::make($request->input('password'));
        }

        $user->save();
        $user->roles()->sync($request->input('roles'));
        $user->sections()->sync($request->input('sections'));

        return redirect(route('users.index'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Создание Пользователя</h2>
            <form action="{{ route('users.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="login">Имя пользователя</label>
                    <input type="text" class="form-control" id="login" name="login">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <h3>Роли</h3>
                @foreach($roles as $role)
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="role-{{ $role->id }}" name="roles[]" value="{{ $role->id }}" {{ $role->name == 'jury' ? 'checked' : '' }}>
                    <label class="form-check-label" for="role-{{ $role->id }}">{{ $role->name }}</label>
                </div>   
                @endforeach
                <br>
                <h3>Секции</h3>
                @foreach($sections as $section)
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="section-{{ $section->id }}" name="sections[]" value="{{ $section->id }}">
                    <label class="form-check-label" for="section-{{ $section->id }}">{{ $section->name }}</label>
                </div>   
                @endforeach
                <br>
                <br>
                <input type="submit" value="Создать Пользователя" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Редактирование Пользователя</h2>
            <form action="{{ route('users.update', $user) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="login">Имя пользователя</label>
                    <input type="text" class="form-control" id="login" name="login" value="{{ $user->name }}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}">
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <h3>Роли</h3>
                @foreach($roles as $role)
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="role-{{ $role->id }}" name="roles[]" value="{{ $role->id }}" {{ $user->roles->contains($role) ? 'checked' : '' }}>
                    <label class="form-check-label" for="role-{{ $role->id }}">{{ $role->name }}</label>
                </div>   
                @endforeach
                <br>
                <h3 class="mt-3">Секции</h3>
                @foreach($sections as $section)
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="section-{{ $section->id }}" name="sections[]" value="{{ $section->id }}" {{ $user->sections->contains($section) ? 'checked' : '' }}>
                    <label class="form-check-label" for="section-{{ $section->id }}">{{ $section->name }}</label>
                </div>   
                @endforeach
                <br>
                <br>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Пользователи</h2>
        <a href="{{ route('users.create') }}" class="btn btn-primary mt-5 mb-5 float-right">Добавть Пользователя</a>
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Имя пользователя</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @forelse($users as $user)
                <tr>
                    <th scope="row">{{ $user->id }}</th>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                    <td><a href="{{ route('users.edit', $user) }}">Редактировать</a></td>
                </tr>
                @empty
                    <td colspan=5>Пусто</td>
                @endforelse
            </tbody>
            </table>
        </div>
    </div>
</div>
@endsection