routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'auth.admin'])->group(function() {
    //USERS
    Route::resource('/users', 'App\Http\Controllers\UsersController')->except(['show', 'destroy']);

    //SECTIONS
    Route::resource('/sections', 'App\Http\Controllers\SectionsController')->except(['show', 'destroy']);
    
    //CONSOLIDATE
    Route::get('/consolidate', 'App\Http\Controllers\ConsolidateController@index')->name('consolidate');
    Route::get('/consolidate/{section}', 'App\Http\Controllers\ConsolidateController@show')->name('consolidate.show');
});

Route::middleware(['auth', 'auth.jury'])->group(function() {
    //PROJECTS
    Route::resource('/projects', 'App\Http\Controllers\ProjectsController');

    //CHECK
    Route::get('/check', 'App\Http\Controllers\CheckController@index')->name('checklist');
    Route::get('/check/{project}', 'App\Http\Controllers\CheckController@check')->name('check');
    Route::post('/check/{project}', 'App\Http\Controllers\CheckController@store')->name('check.store');
    Route::get('/check/{project}/edit', 'App\Http\Controllers\CheckController@edit')->name('check.edit');
    Route::get('/check/{project}/show', 'App\Http\Controllers\CheckController@show')->name('check.show');
    Route::put('/check/{project}/update', 'App\Http\Controllers\CheckController@update')->name('check.update');
});

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Result;

class Section extends Model
{
    use HasFactory;

    public $fillable = ['name', 'active'];

    public function scopeActive($query) 
    {
        return $query->where('active', 1);
    }

    public function users()
    {
        return $this->belongsToMany('App\Models\User', 'user_section');
    }

    public function projects()
    {
        return $this->hasMany('App\Models\Project');
    }

    public function getCheckProgress()
    {
        $projectIds = $this->projects->pluck('id');
        $resultsQuantity = Result::whereIn('project_id', $projectIds)->count();
        if ($this->projects->count() == 0 || $this->users->count() == 0) {
            return 100;
        }
        return round($resultsQuantity / ($this->users->count() * $this->projects->count()), 2) * 100;
    }
}

app/Http/Controllers/SectionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Section;

class SectionsController extends Controller
{
    public function index() 
    {
        $sections = Section::all();
        return view('sections.index', compact(['sections']));
    }

    public function create() 
    {
        return view('sections.create');
    }

    public function store(Request $request) 
    {
        $sections = Section::create([
            'name' => $request->input('name'),
        ]);

        return redirect(route('sections.index'));
    }

    public function edit(Section $section) 
    {
        return view('sections.edit', compact(['section']));
    }

    public function update(Request $request, Section $section) 
    {
        $section->name = $request->input('name');
        $section->active = $request->input('active') ?? 0;
        $section->save();

        return redirect(route('sections.index'));
    }
}

resources/views/sections/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Создание Секции</h2>
            <form action="{{ route('sections.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="name">Название секции</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <input type="submit" value="Создать Секцию" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/sections/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Редактирование секции</h2>
            <form action="{{ route('sections.update', $section) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Название секции</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ $section->name }}">
                </div>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="1" name="active" id="defaultCheck1" {{ $section->active ? 'checked' : '' }}>
                    <label class="form-check-label" for="defaultCheck1">
                        Активность
                    </label>
                </div>
                <br>
                <br>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/sections/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Секции</h2>
        <a href="{{ route('sections.create') }}" class="btn btn-primary mt-5 mb-5 float-right">Добавть Секцию</a>
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Название секции</th>
                <th scope="col">Активность</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @forelse($sections as $section)
                <tr>
                    <th scope="row">{{ $section->id }}</th>
                    <td>{{ $section->name }}</td>
                    <td class="{{ $section->active ? 'text-success' : 'text-danger' }}">{{ $section->active ? 'Активна' : 'Неактивна' }}</td>
                    <td><a href="{{ route('sections.edit', $section) }}">Редактировать</a></td>
                </tr>
                @empty
                    <td colspan=5>Пусто</td>
                @endforelse
            </tbody>
            </table>
        </div>
    </div>
</div>
@endsection